[profile.default]
fail-fast = false
threads-required = "num-cpus"

[profile.ci.junit]
path = "ci.xml"
report-name = "deku_string"

[profile.ci-all.junit]
path = "ci-all.xml"
report-name = "deku_string"

[profile.mutants]
fail-fast = true

[profile.default-miri]
fail-fast = true
success-output = "final"
